const fs = require('fs');

// Safety guard: Don't overwrite local config if running outside Vercel
if (fs.existsSync('firebase-config.js') && !process.env.VERCEL && !process.env.FORCE_GENERATE) {
  console.log('firebase-config.js already exists locally. Skipping generation to protect your local credentials.');
  process.exit(0);
}

// Log presence of keys for debugging (values are masked for security)
const keys = ['apiKey', 'authDomain', 'projectId', 'storageBucket', 'messagingSenderId', 'appId'];
const envKeys = ['FIREBASE_API_KEY', 'FIREBASE_AUTH_DOMAIN', 'FIREBASE_PROJECT_ID', 'FIREBASE_STORAGE_BUCKET', 'FIREBASE_MESSAGING_SENDER_ID', 'FIREBASE_APP_ID'];

console.log('--- Environment Variables Check ---');
keys.forEach((key, index) => {
  const hasCamel = !!process.env[key];
  const hasUpper = !!process.env[envKeys[index]];
  console.log(`${key} (camelCase): ${hasCamel ? 'FOUND' : 'MISSING'}`);
  console.log(`${envKeys[index]} (UPPERCASE): ${hasUpper ? 'FOUND' : 'MISSING'}`);
});
console.log('-----------------------------------');

const config = `// Firebase Configuration for SettleUp
// Auto-generated by generate-config.js
const firebaseConfig = {
  apiKey: "${process.env.apiKey || process.env.FIREBASE_API_KEY || ''}",
  authDomain: "${process.env.authDomain || process.env.FIREBASE_AUTH_DOMAIN || ''}",
  projectId: "${process.env.projectId || process.env.FIREBASE_PROJECT_ID || ''}",
  storageBucket: "${process.env.storageBucket || process.env.FIREBASE_STORAGE_BUCKET || ''}",
  messagingSenderId: "${process.env.messagingSenderId || process.env.FIREBASE_MESSAGING_SENDER_ID || ''}",
  appId: "${process.env.appId || process.env.FIREBASE_APP_ID || ''}"
};
`;

fs.writeFileSync('firebase-config.js', config);
console.log('firebase-config.js generated successfully.');
