const fs = require('fs');

// Safety guard: Don't overwrite local config if running outside Vercel
if (fs.existsSync('firebase-config.js') && !process.env.VERCEL && !process.env.FORCE_GENERATE) {
  console.log('firebase-config.js already exists locally. Skipping generation to protect your local credentials.');
  process.exit(0);
}

const config = `// Firebase Configuration for SettleUp
// Auto-generated by generate-config.js
const firebaseConfig = {
  apiKey: "${process.env.FIREBASE_API_KEY || ''}",
  authDomain: "${process.env.FIREBASE_AUTH_DOMAIN || ''}",
  projectId: "${process.env.FIREBASE_PROJECT_ID || ''}",
  storageBucket: "${process.env.FIREBASE_STORAGE_BUCKET || ''}",
  messagingSenderId: "${process.env.FIREBASE_MESSAGING_SENDER_ID || ''}",
  appId: "${process.env.FIREBASE_APP_ID || ''}"
};
`;

fs.writeFileSync('firebase-config.js', config);
console.log('firebase-config.js generated successfully.');
